config/routes.rb
BadgeApp::Application.routes.draw do
	
  get "sessions/new"

	resources :users
	resources :admins
	resources :badges
	resources :sessions, :only => [:new, :create, :destroy]
	
	match '/register', :to => 'users#new'
	match '/regadmin', :to => 'admins#new'
	match '/createbadge', :to => 'badges#new'
	match '/signin',    :to => 'sessions#new'
	match '/signout',  :to => 'sessions#destroy'
	match '/badges/:id/tag', :to => 'badges#tag', :as => 'tag'

	get "pages/home"
	get "pages/contact"
	get "pages/about"
	get "pages/help"
	get "pages/admin"

	match '/admin', :to => 'pages#admin'
	match '/contact', :to => 'pages#contact'
	match '/about', :to => 'pages#about'
	match '/help', :to => 'pages#help'
	root :to => 'pages#home'
 

end

app/models/badge.rb
class Badge
  include MongoMapper::Document
  
  attr_accessor :tag

  key :title, String, :length => { :maximum => 25 }
  key :description, String, :length => { :maximum => 140 }, :default => ""
  key :tags, Array
  timestamps!
   
  # Relationships.
  many :users
  
  #validations
  validates_presence_of :title
  validates_uniqueness_of :title
  
  def add_tag(tag)
	if tag
		  self.tags << tag
		  self.save
	 end
  end	  
	  
end

app/controllers/badges_controller.rb
class BadgesController < ApplicationController
	before_filter :authenticate, :only => [:index, :tag, :tag_add]
	before_filter :admin_user, :only => [:destroy, :new, :edit, :update]
	
	def show
		@badge = Badge.find(params[:id])
		@title = @badge.title
	end	
	
	def new
		@badge = Badge.new
		@title = "Create Badge"
	end

	def create
		@badge = Badge.new(params[:badge])
		if @badge.save
			flash[:success] = "Created Badge!"
			redirect_to @badge
		else
			@title = "Create Badge"
			render 'new'
		end
	end

	def edit
		@badge = Badge.find(params[:id])
		@title = "Edit Badge"
	end
	
	def update
		@badge = Badge.find(params[:id])
		if @badge.update_attributes(params[:badge])
			flash[:success] = "Badge Updated"
			redirect_to @badge
		else
			@title = "Edit Badge"
			render 'edit'
		end
	end
	
	def tag
		@badge = Badge.find(params[:id])
		@title = "Tag Badge"
	end
	
	def tag_add
		@badge = Badge.find(params[:id])
		tag = params[:badge][:tag]
		if tag
			@badge.add_tag(tag)
			flash[:success] = "Badge Tagged"
			redirect_to @badge
		else
			@title = "Tag Badge"
			render 'tag'
		end
	end	
	
	def index
		@title = "Badge Index"
		@badges = Badge.paginate(:page => params[:page])
	end
	
	def destroy
		badge = Badge.find(params[:id])
		if badge
			badge.destroy
		end
		flash[:success] = "Badge Deleted"
	end	
	
	private
	
	def authenticate
		deny_access unless user_signed_in?
	end
	
	def admin_user
		redirect_to(root_path) unless admin_signed_in?
	end	
	
end

app/views/badges/_badge.html.erb
<li> 
	<%= link_to badge.title, badge_path(badge) %>
	| <%= link_to "tag", tag_path(badge) %>
	<% if admin_signed_in? %>
	| <%= link_to "edit", edit_badge_path(badge) %>
	| <%= link_to "delete", badge, :method => :delete, :confirm => "Are you sure?", 
						:title => "Delete #{badge.title}" %>	
	<% end %>
</li>

app/views/badges/edit.html.erb
<h1>Edit Badge</h1>

<%= form_for(@badge) do |f| %>
	<%= render 'shared/error_messages_badge', :object => f.object %>
	<div class="field">
		<%= f.label :title %>
		<%= f.text_field :title %>
	</div>
	<div class="field">
		<%= f.label :description %>
		<%= f.text_area :description %>
	</div>		
	<div class="actions">
		<%= f.submit "Update" %>
	</div>
<% end %>

app/views/badges/index.html.erb
<h1>Badge Index</h1>

<%= will_paginate %>

<ul class="users">
	<%= render @badges %>
</ul>

<%= will_paginate %>

app/views/badges/new.html.erb
<h1>Create Badge</h1>

<% form_for(@badge) do |f| %>
	<%= render 'shared/error_messages_badge', :object => f.object %>
	<div class="field">
		<%= f.label :title %>
		<%= f.text_field :title %>
	</div>
	<div class="field">
		<%= f.label :description %>
		<%= f.text_area :description %>
	</div>		
	<div class="actions">
		<%= f.submit "Update" %>
	</div>
<% end %>

app/views/badges/show.html.erb
<table class="profile" summary="Profile information">
	<tr>
		<td class="main">
			<h1> 
				<%= @badge.title %> 
			</h1>
			<p>
			<strong>Description</strong>  <%= @badge.description %><br />
			</p>
		</td>
		<td class="sidebar round">
			<strong>Title</strong>  <%= @badge.title %><br />
			<strong>URL</strong>     <%= link_to badge_path(@badge), @badge %>
		</td>
	</tr>
</table>

app/views/badges/tag.html.erb
<h1>Tag Badge</h1>

<%= form_for(@badge) do |f| %>
	<%= render 'shared/error_messages_badge', :object => f.object %>
	<div class="field">
		<%= f.label :tags %>
		<%= f.text_field :tags %>
	</div>		
	<div class="actions">
		<%= f.submit "tag_add" %>
	</div>
<% end %>