config/routes.rb
BadgeApp::Application.routes.draw do
	
  get "sessions/new"

	resources :users
	resources :admins
	resources :badges
	resources :sessions, :only => [:new, :create, :destroy]
	
	match '/register', :to => 'users#new'
	match '/regadmin', :to => 'admins#new'
	match '/createbadge', :to => 'badges#new'
	match '/signin',    :to => 'sessions#new'
	match '/signout',  :to => 'sessions#destroy'
	match '/badges/:id/tag', :to => 'badges#tag', :as => 'tag'

	get "pages/home"
	get "pages/contact"
	get "pages/about"
	get "pages/help"
	get "pages/admin"

	match '/admin', :to => 'pages#admin'
	match '/contact', :to => 'pages#contact'
	match '/about', :to => 'pages#about'
	match '/help', :to => 'pages#help'
	root :to => 'pages#home'
 

end

app/models/user.rb
require 'digest'

class User
  include MongoMapper::Document

email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

attr_accessor :password
attr_accessor :password_confirmation

key :name, String, :length => { :maximum => 50 }
key :email, String  
key :encrypted_password, String
key :salt, String
timestamps!

validates_presence_of :name, :email, :password
validates_uniqueness_of :email, :case_sensitive => false 
validates_format_of :email, :with =>email_regex 
validates :password, :confirmation => true, :length => { :within => 6..40 }

before_save :encrypt_password

def has_password? (submitted_password)
	encrypted_password == encrypt(submitted_password)
end

def self.authenticate(email, submitted_password)
	user = find_by_email(email)
	return nil if user.nil?
	return user if user.has_password?(submitted_password)
end

def self.authenticate_with_salt(id, cookie_salt)
	user = find_by_id(id)
	(user && user.salt == cookie_salt) ? user :nil
end


private

def encrypt_password
	self.salt = make_salt if new?
	self.encrypted_password = encrypt(password)
end

def encrypt(string)
	secure_hash("#(salt)--#(string)")
end

def make_salt
	secure_hash("#(Time.now.etc)--#(password)")
end

def secure_hash(string)
	Digest::SHA2.hexdigest(string)
end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_filter :authenticate, :only => [:index, :edit, :update]
	before_filter :correct_user, :only => [:edit, :update]
	before_filter :admin_user, :only => :destroy
	
	def show
		@user = User.find(params[:id])
		@title = @user.name
	end	
	
	def new
		@user = User.new
		@title = "Register"
	end

	def create
		@user = User.new(params[:user])
		if @user.save
			sign_in_user @user 
			flash[:success] = "Welcome to the Badge App!"
			redirect_to @user
		else
			@title = "Register"
			render 'new'
		end
	end

	def edit
		@title = "Edit User"
	end
	
	def update
		@user = User.find(params[:id])
		if @user.update_attributes(params[:user])
			if admin_signed_in?
				@admin = current_admin
				@admin.update_attributes(params[:user])
			end
			flash[:success] = "Profile Updated"
			redirect_to @user
		else
			@title = "Edit user"
			render 'edit'
		end
	end
	
	def index
		@title = "User Index"
		@users = User.paginate(:page => params[:page])
	end
	
	def destroy
		user = User.find(params[:id])
		if user
			admin = Admin.find_by_email(user.email)
			if admin
				admin.destroy
			end
			user.destroy
		end
		flash[:success] = "User deleted"
	end
	
	private
	
	def authenticate
		deny_access unless user_signed_in?
	end
	
	def correct_user
		@user = User.find(params[:id])
		redirect_to(root_path) unless current_user?(@user)
	end
	
	def admin_user
		redirect_to(root_path) unless admin_signed_in?
	end
	

end

app/helpers/users_helper.rb
module UsersHelper

def gravatar_for(user, options = { :size => 50 } )
	gravatar_image_tag(user.email.downcase, :alt => user.name,
								  :class => 'gravatar',
								  :gravatar => options )
end

end

app/views/users/_user.html.erb
<li> 
	<%= gravatar_for user, :size => 40 %>
	<%= link_to user.name, user %>
	<% if admin_signed_in? %>
	| <%= link_to "delete", user, :method => :delete, :confirm => "Are you sure?", 
						:title => "Delete #{user.name}" %>
	<% end %>
</li>

app/views/users/edit.html.erb
<h1>Edit user</h1>

<%=form_for(@user) do |f| %>
	<%= render 'shared/error_messages_user', :object => f.object %>
	<div> class="field">
		<%= f.label :name %>
		<%= f.text_field :name %>
	</div>
	<div> class="field">
		<%= f.label :email %>
		<%= f.text_field :email %>
	</div>	
	<div> class="field">
		<%= f.label :password %>
		<%= f.password_field :password %>
	</div>
	<div> class="field">
		<%= f.label :password_confirmation, "Confirmation" %>
		<%= f.password_field :password_confirmation %>
	</div>	
	<div class="actions">
		<%= f.submit "Update" %>
	</div>
<% end %>

<div>
	<%= gravatar_for @user %>
	<a href="http://gravatar.com/emails">change</a>
</div>

app/views/users/index.html.erb
<h1>User Index</h1>

<%= will_paginate %>

<ul class="users">
	<%= render @users %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<h1>Register</h1>

<% form_for(@user) do |f| %>
	<%= render 'shared/error_messages_user', :object => f.object %>
	<div class="field">
		<%= f.label :name %></br>
		<%= f.text_field :name %>
	</div>
	<div class="field">
		<%= f.label :email %></br>
		<%= f.text_field :email %>
	</div>
	<div class="field">
		<%= f.label :password %></br>
		<%= f.password_field :password %>
	</div>
	<div class="field">
		<%= f.label :password_confirmation, "Confirmation" %></br>
		<%= f.password_field :password_confirmation %>
	</div>
	<div class="actions">
		<%= f.submit "Register" %>
	</div>
<% end %>

app/views/users/show.html.erb
<table class="profile" summary="Profile information">
	<tr>
		<td class="main">
			<h1> 
				<%= gravatar_for @user %>
				<%= @user.name %> 
			</h1>
		</td>
		<td class="sidebar round">
			<strong>Name</strong>  <%= @user.name %><br />
			<strong>URL</strong>     <%= link_to user_path(@user), @user %>
		</td>
	</tr>
</table>