config/routes.rb
BadgeApp::Application.routes.draw do
	
  get "sessions/new"

	resources :users
	resources :admins
	resources :badges
	resources :sessions, :only => [:new, :create, :destroy]
	
	match '/register', :to => 'users#new'
	match '/regadmin', :to => 'admins#new'
	match '/createbadge', :to => 'badges#new'
	match '/signin',    :to => 'sessions#new'
	match '/signout',  :to => 'sessions#destroy'
	match '/badges/:id/tag', :to => 'badges#tag', :as => 'tag'

	get "pages/home"
	get "pages/contact"
	get "pages/about"
	get "pages/help"
	get "pages/admin"

	match '/admin', :to => 'pages#admin'
	match '/contact', :to => 'pages#contact'
	match '/about', :to => 'pages#about'
	match '/help', :to => 'pages#help'
	root :to => 'pages#home'
 

end

app/views/pages/about.html.erb
<h1>About This App</h1>
<p>
	This is a simple app designed for testing puposes 
	that combines users, admins, badges and email.
</p>

app/views/pages/admin.html.erb
<h1>Admin Page</h1>
<p>
	This page is for site administration.
</p>
<div>
	<ul>
		<% if !admin_signed_in? %>
		<li> <%= link_to "Reg Admin", regadmin_path, :class => "signup_button round" %></li>
		<% else %>
		<li> <%= link_to "Users", users_path, :class => "signup_button round" %></li>	
		<li> <%= link_to "Admins", admins_path, :class => "signup_button round" %></li>
		<li> <%= link_to "Badges", badges_path, :class => "signup_button round" %> </li>
		<li> <%= link_to "Make", createbadge_path, :class => "signup_button round" %> </li>
		<% end %>
	</ul>
</div>

app/views/pages/contact.html.erb
<h1>Contact</h1>
<p>
	This is the contact page for the sample Badge app.
</p>

app/views/pages/help.html.erb
<h1>Help</h1>
<p>
	How to use this App:
</p>

app/views/pages/home.html.erb
<h1>Badge App</h1>
<p>
	This is the home page for the sample Badge app.
</p>
<div>
<ul>
<% if !user_signed_in? %>
<li> <%= link_to "Register", register_path, :class => "signup_button round" %> </li>
<% else %>
<li> <%= link_to "Users", users_path, :class => "signup_button round" %> </li>
<li> <%= link_to "Badges", badges_path, :class => "signup_button round" %> </li>
<% end %>
</ul>
</div>